# Generated by Django 6.0 on 2025-12-18 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsappConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre identificativo de la conexión', max_length=100)),
                ('phone_number_id', models.CharField(help_text='ID del número en Meta/WhatsApp Business API', max_length=50, unique=True)),
                ('access_token', models.TextField(help_text='Token de acceso permanente o de larga duración')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
