# Generated by Django 6.0 on 2025-12-18 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chatbot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre interno del bot (ej: Ventas, Soporte)', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('slug', models.SlugField(help_text='Identificador único para usar en el código (ej: bot_ventas)', unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='whatsappconnection',
            name='verify_token',
            field=models.CharField(default='token_por_defecto', help_text='Token de verificación para configurar en Meta', max_length=100),
        ),
        migrations.AddField(
            model_name='whatsappconnection',
            name='chatbot',
            field=models.ForeignKey(blank=True, help_text='El chatbot que gestionará esta línea', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='connections', to='whatsapp_manager.chatbot'),
        ),
    ]
