# Generated by Django 6.0 on 2025-12-18 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_manager', '0002_chatbot_whatsappconnection_verify_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappconnection',
            name='display_phone_number',
            field=models.CharField(blank=True, help_text='Número real con código de país (sin +) para generar el enlace wa.me', max_length=20, null=True),
        ),
    ]
