# Generated by Django 6.0 on 2025-12-23 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_manager', '0004_webhooklog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wa_id', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('body', models.TextField(blank=True)),
                ('media_file', models.CharField(blank=True, max_length=255, null=True)),
                ('msg_type', models.CharField(default='text', max_length=20)),
                ('direction', models.CharField(choices=[('inbound', 'Entrante'), ('outbound', 'Saliente')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='whatsapp_manager.whatsappconnection')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
