# Generated by Django 6.0 on 2026-01-07 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_manager', '0001_initial'),
        ('whatsapp_manager', '0005_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappconnection',
            name='client',
            field=models.ForeignKey(blank=True, help_text='Cliente externo propietario de esta conexión', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='api_manager.apiclient'),
        ),
    ]
